language: node_js
node_js:
- "9"
script:
- ng build --prod --aot --build-optimizer
before_deploy:
- ng build --prod --aot --build-optimizer
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: GKtYWcZlE6MFa1Gg1p+RYqoK1nokvn4IzB+vx+eMkOpcr3aWLp4aqDVmsHpiIxgObvm6ozDxtpz5ldM+vs1OVlBPrZoMoLIf3EQXD3DqyGCH6qhjETekjAQ48hHS8QGFvYe5nRm7V6UMAqwWbRIKMs2NK9C/UK8lVmt/N/Lw4w36bnJMOyGLIjJaPM1tWrhSNZmuLASqvwprW5RA2joa+r5+mcWXhsg3EkoDtMFnkNqW0YF22zbGiaWqOIS08WXSs1XpYA2pt0pt683cYz6I3pERF+yrs0n/rJ8zrNxxive5noqEG9RFB7Bp715KCYgdujZ+26sfIsBKgXpEpe1dh+h1iqTTKcIbHn/sOWNnOVeEwefSexHspEvlhfHYBu6rbjotwDbuicH97eLaGfntGOElFHbYXiTz7GLlzuDsPPHj3pITib83QqYS5DvDCIHYAJQZvzGvi3DDj3NxbXRCwUN5qq9fUEvLfJIDoJfP6G3+f7ogwBF8u/UoMNffSIFfYCbZ4pKMRBTLKEtCPssvgIew+ZAmpxI2u6YL0kHcbQ2j6wgNkrHrVq0hN2pmW74udJLSFpkMQY9fAVi8FPiUTCkL1s8JsxnPUhyTR1pIG0GmC1fOE8Q3RMBSe/NoYs33DHWQdWnP2b2Nzq1UxITl/acLzUNvGIFnmzmQRWuCvEU=
  on:
    branch: master
