language: node_js
node_js:
- node
script:
- ng build --prod --aot --build-optimizer
before_deploy:
- ng build --prod --aot --build-optimizer
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $token
  on:
    branch: master
env:
  global:
    secure: SlKP11wNFGkVvwaSADnIwejJ4q0uEp2LnOtCvjZ/iYQGpXWsZL+RK00MqyinYDFUoLAm04yz6k/UffIobwhuF3U+wdkHNjEcucFtk3/oV4DM2fWVV1cFkg7eyihd6p/OSEXGCDxtZ8FdqY/FOjsX+QQA+r4ProqX/04iSHL7Sh0tk7d4+GaD/0wxoDB2SCx9BPfmEVIxRe3PhTujn2FXRbdpflFwX/FBXcxQ+K2KEqjovr3NAIF39E7bMtSmfNVa4XokbM1fQ0C0KrFAosnTbgWD5TJumOwRAMq0rLbO0Bm70VlbD4JqFjqZ97MPdrh7qRdF+XvCCFU08Do0OuhlZfcsL960fktNBYBK6AF9GGNDpVv5djztBubifaz6WW25A2L69XmynIpeVapNnJq5VJlpLn8J3xaTkpTG8HdnnLIjSD4sUB2VFKgKybZJe4uwzJ0wjfDCzDe2Tk895tVmUpGxumOD9k49FxM83nlHdoNUyWfwPHYzY3zr7crwuQbIL6PEKWRcN4OD0WOGWPwHa00/o/ayMR4ILgwDZ0kHc8jpa9nDj0WhjvZ9hW4VFlLqbdwRr+8q6QuUVSyYWKC/ZApr+8xQida5hsv2EGeTlmGUBJ+ycOy9MxPi3vQhMKNgqAxF+ZlJpKf4BdpPM02QQ1IZJWxzuhsqA94zWwtBIzs=
