language: node_js
node_js:
- '9'
script:
- ng build --prod --aot --build-optimizer
before_deploy:
- ng build --prod --aot --build-optimizer
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: WfoLjk+CTyGYN3GFe/rLjca7jEFrePUdNdh6dtr8lyfnoNA/M8vegePtDzaUKtPne2+8dIZkejEHzfL0ckkJoXBQ2yiBSWPZjO7SdJmIpdNTe4rcs+QQSaQI6Regh5J+gXbMSjGXPW3SgU2vZ4ukh9R8fvBKgBMhV2hlhbYLXxPSiVF7LlrmrZB6wPZj7cra3SRyDuLjiOUWv48WHn8WPunHUbwiQdU12/PW6QB0T+yMPYaFcqjrpQ7n1WrBp78BmDuSZIobtO69b1I7/CLZKTUWGWQb05LalYMqo34W8Bj+g3t/y3wIYSSgXIE4Z4g7kjRFgpJrdT+eCi+fi33QxVTIck8WJFh9O5lIuTh8ewbxc9X5piunEHgFrG4w0J6h3zyNGmoKmL6zprtH5d8mLaLkL4pDmHZcvuwcMr4yBOM+MlMs9WAULQn17PYqVdVYqhyLPBinBy9S4zQIXkUhowrOFVSr4TWKblfcOcY2p6Ahn9ESs4Pns8uzLo7nk1riKtJRwxmVTmbwMMLi7OhmKbdjkpZnouyh0Lk0PX6qzr705jS18P+NFnmRLvHxXEwRB4WCcIWbyfd6freKi2C2ytfZxb8k2Tk+pPFSwGU95TssCceCTwmeNvB7lRVrdStPXY+juKLNFy6SSXLf8lmwULtGKuOl6BMPKw7QDHWxszo=
  on:
    branch: master
